### ISSUE TITLE
Execution failed for task ':app:mergeDexRelease'.

### ISSUE THREAD

**Issue by quyetthang122** [react-native-masked-view/masked-view#100]
Hi There,

I am experiencing this issue, you guys have any ideas about this one?

`* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
     Type org.reactnative.maskedview.BuildConfig is defined multiple times: /Users/fcv-0050/Documents/Thang-Project/fcblog/fcblogDeveloper/node_modules/@react-native-community/masked-view/android/build/.transforms/a653cad861d1364c06ae4f083cd01020/classes/classes.dex, /Users/fcv-0050/Documents/Thang-Project/fcblog/fcblogDeveloper/node_modules/@react-native-masked-view/masked-view/android/build/.transforms/cb6b46470fd83b705ad0ac476848736e/classes/classes.dex
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings`

**Comment by Talha-Jawed** [comment]
same issue

**Comment by SaeedSyedAli96** [comment]
I am also having same issue

**Comment by Arturo-J-Alva** [comment]
I too

**Comment by ohmdob** [comment]
add this line to gradle.properties

# org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m

**Comment by Navipro70** [comment]
Same here

**Comment by Navipro70** [comment]
Resolved:
I have two packages `@react-native-masked-view/masked-view` (from previous developer) and `@react-native-community/masked-view`.
Just remove `@react-native-masked-view/masked-view` package and try build.

**Comment by NgocLe1001** [comment]
@Navipro70 thank you so much <3

**Comment by Mihai-github** [comment]
> Resolved:
> I have two packages `@react-native-masked-view/masked-view` (from previous developer) and `@react-native-community/masked-view`.
> Just remove `@react-native-masked-view/masked-view` package and try build.
> 
> @FonDorn close this one please

Works, thx 👍

**Comment by Naturalclar** [comment]
Closing as the issue seems to be resolved, thanks!

**Comment by vipulchakravarthy** [comment]
> Resolved: I have two packages `@react-native-masked-view/masked-view` (from previous developer) and `@react-native-community/masked-view`. Just remove `@react-native-masked-view/masked-view` package and try build.
> 
> @FonDorn close this one please

You saved my day man!!!

**Comment by tientruongvan1995** [comment]
> Resolved: I have two packages `@react-native-masked-view/masked-view` (from previous developer) and `@react-native-community/masked-view`. Just remove `@react-native-masked-view/masked-view` package and try build.
> 
> @FonDorn close this one please

our savior :D

**Comment by kamranayub40** [comment]
Great save my Day

**Comment by vjha125** [comment]
@Navipro70 hey this is not working for me.
* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
i'm facing this issue when i make a release build in react native.

**Comment by vjha125** [comment]
> @Navipro70 hey this is not working for me.
> 
> * What went wrong:
>   Execution failed for task ':app:mergeDexRelease'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > i'm facing this issue when i make a release build in react native.

please help
