### ISSUE TITLE
npm only has 1.1.10 version

### ISSUE THREAD

**Issue by hexiangyuan** [react-native-masked-view/masked-view#103]
yarn add @react-native-masked-view/masked-view
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "@react-native-community/masked-view@0.2.0". Ignoring it.
Couldn't find any versions for "@react-native-community/masked-view" that matches "0.2.0"
? Please choose a version of "@react-native-community/masked-view" from this list: (Use arrow keys)
❯ 0.1.10 
  0.1.9 
  0.1.8 
  0.1.7 
  0.1.6 
  0.1.5 
  0.1.4 
  0.1.3 
  0.1.2 
  0.1.1 
  0.1.0 
  0.0.5 
  0.0.4 
  0.0.3

**Comment by Naturalclar** [comment]
@hexiangyuan Thanks for raising the issue!

This package has been renamed to `@react-native-masked-view/masked-view` from version `0.2.0`.

Please see this issue comment for reasonings and details behind it.

https://github.com/react-native-community/discussions-and-proposals/issues/176
