### ISSUE TITLE
Have to use npm install --force on react-native 0.64.0 projects

### ISSUE THREAD

**Issue by Darapsas** [react-native-masked-view/masked-view#112]
It would be nice to see a new release, getting this when trying to install every time, gets kinda annoying (works when using `npm install --force` or `yarn install`):

![Screenshot 2021-03-30 at 13 52 26](https://user-images.githubusercontent.com/20926795/112979051-c0a72700-9160-11eb-9c23-94c718448a10.png)

**Comment by Shahanshah87** [comment]
+1

**Comment by sami-99** [comment]
+1

**Comment by marius4896** [comment]
+1

**Comment by Naturalclar** [comment]
The peerDependency in the latest version is set to >0.57.
Please use the `@react-native-masked-view/masked-view` package
