### ISSUE TITLE
Animated masked view no longer works on android <= 9

### ISSUE THREAD

**Issue by LouiseBC** [react-native-masked-view/masked-view#117]
The problem:
I use MaskedView with an animating circle as a mask to animate a component's background in and out. The mask still works, but the animation doesn't. I.e., I need to reload the page to see the state change (background visible/invisible)

This was introduced by #116 -- I've checked that reverting this change solves the problem.

**Comment by clintjansen** [comment]
Also facing this issue, anything animated inside of MaskedView does not animate on Android. 
This seemed to be an issue before: #22

**Comment by k-ibr** [comment]
@LouiseBC can you perhaps share an example project, I tried to recreate this but unsuccessful, we managed to animate our objects. With it I can investigate further.

**Comment by clintjansen** [comment]
```     
import { Animated, Image } from 'react-native';
import MaskedView from '@react-native-masked-view/masked-view';

...

    const loadingProgress = useRef(new Animated.Value(0)).current;
           
    Animated.timing(loadingProgress, {
        toValue: 100,
        duration: 1000,
        useNativeDriver: true,
    }).start();

```
        <MaskedView
            style={{ flex: 1, height: '100%' }}
            maskElement={
                <Animated.Image
                    source={imageSource}
                    style={[
                        {
                            width: 255,
                            height: 255,
                        },
                        {
                            transform: [
                                {
                                    scale: loadingProgress.interpolate({
                                        inputRange: [0, 10, 100],
                                        outputRange: [1, 0.8, 70],
                                    }),
                                },
                            ],
                        },
                    ]}
                />
            }>
            {/* Content */}
        </MaskedView>
       
The image animates when I place it out of MaskedView.
And it also animates with the first release of this package, albeit with very laggy performance

**Comment by k-ibr** [comment]
I have tried to look for solutions but haven't been able to find anything that solves this with good performance. Perhaps that one of the maintainers can have an in-depth look at  this? 

@FonDorn @Naturalclar ?
