### ISSUE TITLE
Publish v0.2.5 for @react-native-community/masked-view

### ISSUE THREAD

**Issue by luisnaranjo733** [react-native-masked-view/masked-view#131]
Hi,

Could someone please publish v0.2.5 for the older @react-native-community/masked-view npm namespace?
react-navigation still [points ](https://reactnavigation.org/docs/getting-started/#installation)to this apparently older npm namespace, so it's non-trivial for apps that use react-navigation to migrate npm namespaces.

Older namespace (needs a v0.2.5 publish): https://www.npmjs.com/package/@react-native-community/masked-view
Newer namespace (I assume this is newer, because it has the latest package ver): https://www.npmjs.com/package/@react-native-masked-view/masked-view

@Naturalclar - can you help? I see you are the latest publisher for both packages.

**Comment by luisnaranjo733** [comment]
Filed a bug on react-navigation to update to the correct version of this package 
https://github.com/react-navigation/react-navigation/issues/9776

**Comment by Naturalclar** [comment]
@luisnaranjo733 

Hello :wave:

I'm not planning on releasing new version of the `@react-native-community` namespace, as that would cause more confusion for which version to actually use.

Instead, could you install the package in new namespace, and edit your metro config as follows?


```
// metro.config.js

module.exports = {
	...
	resolver: {
		extraNodeModules: {
			'@react-native-community/masked-view': require.resolve('@react-native-masked-view/masked-view'),
		}
	}
}

```

This should set all imports (including the ones in react-navigation) to get the masked view in the new namespace

**Comment by luisnaranjo733** [comment]
That makes sense. I'll give that or a patch file a try. react-navigation also clarified in my other issue that they are not planning to upgrade react-navigation@5, which also clarifies this.

Thanks for the response!
