### ISSUE TITLE
Updates package compatibility with expo

### ISSUE THREAD

**Issue by carlos3g** [react-native-masked-view/masked-view#137]
Today, the last version of [@react-native-masked-view/masked-view](https://github.com/react-native-masked-view/masked-view) compatible with expo is `v0.2.4` and it comes with a lot of complications since we can't use animations in `maskedElement` for android in this version. So, I'm here to ask you to make the last version of this package compatible with expo

**Comment by Naturalclar** [comment]
In order to get the latest version working on expo, you'd have to ask the expo team, or use bare workflow of expo, as managed workflow of expo only supports a set version.
Nothing can be done from the library side, sorry about that.
