### ISSUE TITLE
Issue with prop types in typescript 4.6.2

### ISSUE THREAD

**Issue by 0xAsimetriq** [react-native-masked-view/masked-view#149]
Just updated to latest typescript version and got following ts error on `MaskedView` component:

Found possibly related issue on StackOverflow
https://stackoverflow.com/a/69221278/911930

<img width="771" alt="Screenshot 2022-03-16 at 13 06 59" src="https://user-images.githubusercontent.com/3154053/158576748-243aecb8-4dd9-4b53-b7d4-86ffe957bfef.png">

**Comment by Mafooch** [comment]
Same

**Comment by TomCorvus** [comment]
You can open _node_modules/@react-native-masked-view/masked-view/types/index.d.ts_ and change this:
```
declare class MaskedViewComponent extends React.Component<MaskedViewProps> {}
declare const MaskedViewBase: ReactNative.Constructor<
  ReactNative.NativeMethods
> &
  typeof MaskedViewComponent;
export default class MaskedView extends MaskedViewBase {}
```

into

```
declare class MaskedViewComponent extends React.Component<MaskedViewProps> {}
export default class MaskedView extends MaskedViewComponent {}
```

**Comment by altarrok** [comment]
pls fix this

**Comment by mbenmass** [comment]
pls fix this

**Comment by eprice122** [comment]
+1

**Comment by m-frost-fd** [comment]
I ran into the same issue. This worked for me: https://stackoverflow.com/a/74145168

I added `"react": ["node_modules/@types/react"]` to my tsconfig.json file:

```{
    ...
    "compilerOptions": {
        ...
        "paths": {
            "react": ["node_modules/@types/react"]
        }
    }
}```

**Comment by Pulimet** [comment]
The repository was moved to @react-native-masked-view/masked-view. This will resolve the issue.

**Comment by Naturalclar** [comment]
Closing Issue as it is resolved.
