### ISSUE TITLE
Draggable mask to adaptively reveal underlying image? 

### ISSUE THREAD

**Issue by sjburwell** [react-native-masked-view/masked-view#158]
I am using `PanResponder`, `MaskedView`, and `Animated.View` in React-Native to try to create a dynamic mask that changes as the user drags their finger across the screen. The goal is to keep the majority of the image concealed and only show parts of the image where the finger is touching the screen. Gestures will be recorded (i.e., screen coordinates where the person has "searched" the image, "dwell time", etc.) for data analysis.

For example, a user may be presented with the below screen:
![image](https://user-images.githubusercontent.com/34345358/172171254-f4be16fa-bded-4513-9604-da5f8a262045.png)

The user may drag the circle to different locations on the screen explore the underlying image, like below: 
![image](https://user-images.githubusercontent.com/34345358/172171348-0bbc0110-aca1-4972-8644-3ff3829c7d34.png)

I have coded the mask based on tutorials for PanResponder and MaskedView, but the screen is not responsive. In other words, I am unable to drag the circle around the screen. I believe I have possibly ordered operations incorrectly or mistakenly hard coded the mask in its position?

Can anyone spot what might be wrong from my code?

```
import React, { useRef } from 'react';
import { Animated, View, Image, useWindowDimensions, PanResponder, StyleSheet } from 'react-native';
import MaskedView from '@react-native-masked-view/masked-view';

const App = () => {
  const { width, height } = useWindowDimensions();
  const fromCoords = { x: 175, y: 350 };  
  const pan = useRef(new Animated.ValueXY(fromCoords)).current;
  
  const panResponder = useRef(
    PanResponder.create({
      onMoveShouldSetPanResponder: () => true,
      onPanResponderGrant: () => {
        pan.setOffset({
          x: pan.x._value,
          y: pan.y._value
        });
      },
      onPanResponderMove: Animated.event(
        [
          null,
          { dx: pan.x, dy: pan.y }
        ]
      ),
      onPanResponderRelease: () => {
        Animated.spring(
          pan,
          { toValue: { x: 100, y: 0 } }
        ).start();

      }
    })
  ).current;

  return (
    <View style={styles.container}>
    <MaskedView
      style={{ flex: 1, flexDirection: 'row', height: '100%' }}
      maskElement={
        <Animated.View
          style={{
            transform: [{ translateX: pan.x }, { translateY: pan.y }],
            width: 100,
            height: 100,
            borderRadius: 50,
            backgroundColor: 'black'
          }}
          {...panResponder.panHandlers}>
        </Animated.View>
      }
    >
      <Image
        style={{
          width: width,
          height: height,
        }}
        source={require('./image.jpg')}
      />
    </MaskedView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF',
  },
});

export default App;
```

**Comment by lucy-tran** [comment]
I got it working by speading `{...panResponder.panHandlers}` in `<MaskedView>` instead of `<Animated.View>`

**Comment by sjburwell** [comment]
Very insightful, @lucy-tran, thanks!
