### ISSUE TITLE
Flickers while navigating (Android)

### ISSUE THREAD

**Issue by RajibKDey** [react-native-masked-view/masked-view#160]
MaskedView flickers showing only the underlying color when navigating on android

https://user-images.githubusercontent.com/47169875/173815386-cea97586-bab6-4fbb-9758-e51e6a6dec38.mov

**Comment by erennyuksell** [comment]
i have the same problem. Any solutions?

**Comment by pkunat** [comment]
Struggling with the same problem, no solution so far.

Problem occurs only during `StackNavigator`'s `pop` and `replace` actions, `push` and `jumpTo` (delegating to the nested BottomTabs) work fine.

I tried setting `androidRenderingMode="software"` and it didn't help.

```
    "@react-native-masked-view/masked-view": "0.2.7",

    "@react-navigation/bottom-tabs": "6.0.9",
    "@react-navigation/native": "6.0.6",
    "@react-navigation/native-stack": "6.2.5",
    "@react-navigation/stack": "6.0.11",
```

**Comment by erennyuksell** [comment]
I think our problem is about this function 
`  private void updateBitmapMask() {
    if (this.mBitmapMask != null) {
      this.mBitmapMask.recycle();
    }

    View maskView = getChildAt(0);
    if (maskView != null) {
      maskView.setVisibility(View.VISIBLE);
      this.mBitmapMask = getBitmapFromView(maskView);
      //maskView.setVisibility(View.INVISIBLE);
    } else{
      this.mBitmapMask = null;
    }
  }`

**Comment by unfernandito** [comment]
Hi guys, I hope you are well.

I'll check the library and try to find a fix for your problem.

Could you please post the steps to reproduce the issue and an example video?

Or even a piece of code to reproduce it could be useful.

Regards

**Comment by erennyuksell** [comment]
@unfernandito i found what is causing the problem in my scenario. Unmounting the view after the animation is done is causing the problem. 
![1](https://user-images.githubusercontent.com/43651689/180445655-d39957ed-3c68-4c38-92e1-6f19169d16b2.PNG)
![2](https://user-images.githubusercontent.com/43651689/180445684-c3a577ca-1195-4628-a078-b99a495accc7.PNG)

**Comment by pkunat** [comment]
@erennyuksell In my case the masked element is an icon from `FontAwesome`, so no animations (except for the ones introduced by `react-navigation`). I'm using `MaskedView` to add gradient to the icons.

@unfernandito Sorry for the late response. Here's a minimalistic project that reproduces this bug:
https://gitlab.com/pkunat/maskedview-react-native-navigation-bug-repro/-/tree/master
I tried to do it in codesandbox, but it kept crashing, so I gave up.
All the relevant code is in `App.js` https://gitlab.com/pkunat/maskedview-react-native-navigation-bug-repro/-/blob/master/App.js
As for the video, it's basically what you see in @RajibKDey 's opening post - when the transition animation starts, maskElement disappears and the background element is shown for a brief moment (but only when going from view2 to view1)

**Comment by unfernandito** [comment]
Thanks for the example code, I'll check it and come back with some kind of fix.

It looks like the method which removes sub-children has been executed one by one and It's not removing the entire masked view element at the same time.

**Comment by unfernandito** [comment]
![image](https://user-images.githubusercontent.com/6326186/181782321-eab565e8-5266-4713-9adc-38c20224e2c7.png)

Yes, that's the issue. 

The background element it's been unmounted after the maskedElement causing this strange behavior.

I'll keep looking for a fix.

**Comment by michalgrzelak** [comment]
@unfernandito could you tell us what's the progress? Do you need any help with that?

**Comment by michalgrzelak** [comment]
@unfernandito could you tell us what the progress is? Do you need any help with that?
