### ISSUE TITLE
RN 0.68 and ViewPropTypes deprecation

### ISSUE THREAD

**Issue by onelittlebird** [react-native-masked-view/masked-view#168]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@react-native-masked-view/masked-view@0.2.6` for the project I'm working on.

It is related to version 0.68 of `react-native` where the `ViewPropTypes` import was deprecated.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@react-native-masked-view/masked-view/js/MaskedViewTypes.js b/node_modules/@react-native-masked-view/masked-view/js/MaskedViewTypes.js
index 610e54d..1daced9 100644
--- a/node_modules/@react-native-masked-view/masked-view/js/MaskedViewTypes.js
+++ b/node_modules/@react-native-masked-view/masked-view/js/MaskedViewTypes.js
@@ -1,6 +1,6 @@
 // @flow
 import { type Node, type Element } from 'react';
-import { ViewPropTypes } from 'react-native';
+import { ViewPropTypes } from 'deprecated-react-native-prop-types'
 
 export type MaskedViewProps = typeof ViewPropTypes &
   $ReadOnly<{|
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Dallas62** [comment]
Hi,

`ViewPropTypes` is still present in `@react-native-masked-view/masked-view/js/MaskedViewTypes.js`

**Comment by Naturalclar** [comment]
@jakrim may I ask what version of masked-view you're using? It should be fixed in v0.2.7

**Comment by disrae** [comment]
I'm not sure why the latest version that comes up is not 0.2
![image](https://github.com/react-native-masked-view/masked-view/assets/26100016/8902624f-001c-4dec-9aa2-0ddc2c6c3911)

**Comment by Naturalclar** [comment]
the package has been renamed to `@react-native-masked-view/masked-view`, sorry for the confusion
