### ISSUE TITLE
Add example directory

### ISSUE THREAD

**Issue by Naturalclar** [react-native-masked-view/masked-view#172]
This repo should have an example directory so the repo's features can be tested within the repository.

Use [microsoft/react-native-test-app](https://github.com/microsoft/react-native-test-app) to create an example directory to test masked view

**Comment by LRNZ09** [comment]
@Naturalclar are you working on this? Otherwise, I can take a look at it

**Comment by Naturalclar** [comment]
@LRNZ09 It'll be great if you can take at look at it :+1:

> EDIT: one problem I see with using [microsoft/react-native-test-app](https://github.com/microsoft/react-native-test-app) is that it doesn't support the Web platform yet, see https://github.com/microsoft/react-native-test-app/issues/812, maybe Expo could be a more straightforward option.

Unfortunately, expo wouldn't be suitable for an example app for a native module library as expo doesn't support adding native modules that are not supported by the framework.
I'm aware that masked-view is one of the libraries that are supported by expo but I'd like to keep the library flexible

**Comment by Naturalclar** [comment]
Closed via #176
