### ISSUE TITLE
What is license of package

### ISSUE THREAD

**Issue by piotrpietruszewski99** [react-native-masked-view/masked-view#45]
# Question
The license file is missing

**Comment by EyMaddis** [comment]
according to https://github.com/react-native-community/react-native-masked-view/blob/master/package.json
it is MIT

**Comment by yplakosh** [comment]
Hi @FonDorn 

I see you are listed as an author of this project inside https://github.com/react-native-community/react-native-masked-view/blob/master/package.json

Is it possible to explicitly add a license file with your name and/or any other names needed in the copyright?
