### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by mrdanb** [react-native-masked-view/masked-view#64]
# Feature request

Your `RNCMaskedView.podspec` file references a git tag version yet the repository itself has no tags:
```
{ :git => "https://github.com/react-native-community/react-native-masked-view.git", :tag => "v#{s.version}" }
```

## Why it is needed

To offer the ability to add the library as an independent Cocoapod. At the moment this fails as the podspec specifies a tag which doesn't exist in git

## Possible implementation

Tag each release and push to git. E.g.
```
git tag -a <tag_name>
git push origin <tag_name>
```

**Comment by pinarol** [comment]
We had the exact same problem. Could you please add the necessary tags?

**Comment by FonDorn** [comment]
done
