### ISSUE TITLE
Task :react-native-community_masked-view:javaPreCompileDebug FAILED

### ISSUE THREAD

**Issue by sumanbhattarai** [react-native-masked-view/masked-view#68]
# Bug report

## Summary

Some hours ago my code was running perfectly fine on both android and ios. Now, I got some problems only on android. IOS works perfectly fine.

The error I've got :
Task :react-native-community_masked-view:javaPreCompileDebug FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

Note: I am using Gradle-6.5-all.zip

## Environment info

`react-native info` output:

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 166.99 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 0.1.10

## Steps to reproduce

1. react-native init project
2. npm install react-navigation
3. react-native run-android

Describe what you expected to happen:

1. app to run fine.

**Comment by lhb11** [comment]
解决了吗

**Comment by levim770** [comment]
Hi, I have the same issue, what is the solution to it?
